class Roles:
  
    nfl = [
        "Arizona Cardinals",
        "Atlanta Falcons",
        "Baltimore Ravens",
        "Buffalo Bills",
        "Carolina Panthers",
        "Chicago Bears",
        "Cincinnati Bengals",
        "Cleveland Browns",
        "Dallas Cowboys",
        "Denver Broncos",
        "Detroit Lions",
        "Green Bay Packers",
        "Houston Texans",
        "Indianapolis Colts",
        "Jacksonville Jaguars",
        "Kansas City Chiefs",
        "Las Vegas Raiders",
        "Los Angeles Chargers",
        "Los Angeles Rams",
        "Miami Dolphins",
        "Minnesota Vikings",
        "New England Patriots",
        "New Orleans Saints",
        "New York Giants",
        "New York Jets",
        "Philadelphia Eagles",
        "Pittsburgh Steelers",
        "San Francisco 49ers",
        "Seattle Seahawks",
        "Tampa Bay Buccaneers",
        "Tennessee Titans",
        "Washington Football Team",
    ]

    nfl_logos = [
        "AFC",
        "AFC Championship",
        "Hall Of Fame",
        "NFC",
        "NFC Championship",
        "NFL",
        "Pro Bowl",
        "Supe rBowl",
    ]
  
    nba = [
        "Atlanta Hawks",
        "Boston Celtics",
        "Brooklyn Nets",
        "Charlotte Bobcats",
        "Chicago Bulls",
        "Cleveland Cavaliers",
        "Dallas Mavericks",
        "Denver Nuggets",
        "Detroit Pistons",
        "Golden State Warriors",
        "Houston Rockets",
        "Indiana Pacers",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Memphis Grizzlies",
        "Miami Heat",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "New Orleans Hornets",
        "New York Knicks",
        "Oklahoma City Thunder",
        "Orlando Magic",
        "Philadelphia Sixers",
        "Phoenix Suns",
        "Portland Trail Blazers",
        "Sacramento Kings",
        "San Antonio Spurs",
        "Toronto Raptors",
        "Utah Jazz",
        "Washington Wizards",
    ]

    nba_logos = [
        "All Star",
        "Draft",
        "Eastern Conference",
        "Finals Trophy",
        "NBA",
        "Playoffs",
        "Western Conference",
    ]
    
    mlb = [
        "Atlanta Braves",
        "Miami Marlins",
        "New York Mets",
        "Philadelphia Phillies",
        "Washington Nationals",
        "Chicago Cubs",
        "Cincinnati Reds",
        "Milwaukee Brewers",
        "Pittsburgh Pirates",
        "St. Louis Cardinals",
        "Arizona Diamondbacks",
        "Colorado Rockies",
        "Los Angeles Dodgers",
        "San Diego Padres",
        "San Francisco Giants",
        "Baltimore Orioles",
        "Boston Red Sox",
        "New York Yankees",
        "Tampa Bay Rays",
        "Toronto Blue Jays",
        "Chicago White Sox",
        "Cleveland Indians",
        "Detroit Tigers",
        "Kansas City Royals",
        "Minnesota Twins",
        "Houston Astros",
        "Los Angeles Angels",
        "Oakland Athletics",
        "Seattle Mariners",
        "Texas Rangers",
    ]

    mlb_logos = [
        "ALDS",
        "American League",
        "MLB",
        "MLB Network",
        "National League",
        "NLDS",
        "World Series",
    ]
    
    nhl = [
        "Anaheim Ducks",
        "Arizona Coyotes",
        "Boston Bruins",
        "Buffalo Sabres",
        "Calgary Flames",
        "Carolina Hurricanes",
        "Chicago Blackhawks",
        "Colorado Avalanche",
        "Columbus Blue Jackets",
        "Dallas Stars",
        "Detroit Red Wings",
        "Edmonton Oilers",
        "Florida Panthers",
        "Los Angeles Kings",
        "Minnesota Wild",
        "Montreal Canadiens",
        "Nashville Predators",
        "New Jersey Devils",
        "New York Islanders",
        "New York Rangers",
        "Ottawa Senators",
        "Philadelphia Flyers",
        "Pittsburgh Penguins",
        "San Jose Sharks",
        "Seattle Kraken",
        "St. Louis Blues",
        "Tampa Bay Lightning",
        "Toronto Maple Leafs",
        "Vancouver Canucks",
        "Vegas Golden Knights",
        "Washington Capitals",
        "Winnipeg Jets",
    ]
    
    nhl_logos = [
        "AllStar",
        "Eastern Conference",
        "NHL",
        "NHL Playoffs",
        "Stanley Cup Finals",
        "West Conference",
        "Winner Classic",
    ]
  
    mls = [
        "Atlanta United FC",
        "Chicago Fire FC",
        "Colorado Rapids",
        "Columbus Crew SC",
        "D.C. United",
        "FC Cincinnati",
        "FC Dallas",
        "Houston Dynamo",
        "Inter Miami CF",
        "LA Galaxy",
        "Los Angeles Football Club",
        "Minnesota United FC",
        "Montreal Impact",
        "Nashville SC",
        "New England Revolution",
        "New York City FC",
        "New York Red Bulls",
        "Orlando City SC",
        "Philadelphia Union",
        "Portland Timbers",
        "Real Salt Lake",
        "San Jose Earthquakes",
        "Seattle Sounders FC",
        "Sporting Kansas City",
        "Toronto FC",
        "Vancouver Whitecaps FC",
    ]
    
    fcf = [
        "8oki",
        "Beasts",
        "Bored Ape FC",
        "Glacier Boyz",
        "Kingpins",
        "Knights Of Degen",
        "Shoulda Been Stars",
        "Zappers",
    ]
      
    usfl = [
        "Birmingham Stallions",
        "Houston Gamblers",
        "Michigan Panthers",
        "New Jersey Generals",
        "New Orleans Breakers",
        "Philadelphia Stars",
        "Pittsburgh Maulers",
        "Tampa Bay Bandits",
    ]
      
    xfl = [
        "Arlington Renegades",
        "DC Defenders",
        "Houston Roughnecks",
        "Orlando Guardians",
        "San Antonio Brahmas",
        "Seattle Sea Dragons",
        "St Louis Battlehawks",
        "Vegas Vipers",
    ]

    football_fusion = [
        "Arizona Heat",
        "Atlanta Nighthawks",
        "Baltimore Royals",
        "Buffalo Boars",
        "Carolina Predators",
        "Chicago Bucks",
        "Cincinnati Tigers",
        "Cleveland Braves",
        "Dallas Outlaws",
        "Denver Mustangs",
        "Detroit Lightning",
        "Green Bay Paladins",
        "Houston Drillers",
        "Indianapolis Cubs",
        "Jacksonville Devils",
        "Kansas City Cherokees",
        "Los Angeles Comets",
        "Los Angeles Rage",
        "Miami Sharks",
        "Minnesota Vipers",
        "New England Nationals",
        "New Orleans Knights",
        "New York Greats",
        "New York Juggernauts",
        "Las Vegas Renegades",
        "Philadelphia Raptors",
        "Pittsburgh Stormers",
        "San Francisco Lions",
        "Seattle Cyclones",
        "Tampa Bay Pirates",
        "Tennessee Trojans",
        "Washington Warriors",
    ]

    college = [
        "Alabama Crimson Tide",
        "Auburn Tigers",
        "Boston College Eagles",
        "Buffalo Bulls",
        "Cincinnati Bearcats",
        "Clemson Tigers",
        "Colorado Buffaloes",
        "Georgia Bulldogs",
        "Indiana Hoosiers",
        "Iowa Hawkeyes",
        "Kansas Jayhawks",
        "Maryland Terrapins",
        "Miami Hurricanes",
        "Michigan State Spartans",
        "Michigan Wolverines",
        "Nebraska Cornhuskers",
        "North Carolina Tar Heels",
        "Notre Dame",
        "Ohio State Buckeyes",
        "Oklahoma Sooners",
        "Oregon Ducks",
        "Penn State Nittany Lions",
        "Pittsburgh Panthers",
        "Rutgers Scarlet Knights",
        "Stanford Cardinal",
        "Tennessee Volunteers",
        "Texas Longhorns",
        "USC Trojans",
        "Utah Utes",
        "Virginia Tech:",
        "West Virginia Mountaineers",
        "Wisconsin Badgers",
    ]

    college_logos = [
        "ACC",
        "B10",
        "B12",
        "National Championship",
        "NCAA",
        "RoseBowl",
        "SEC",
        "SugarBowl",
    ]
    
    symbol_pack_1 = [
        "Info",
        "Inquiry",
        "Prohibited",
        "Warn",
    ]
    
    symbol_pack_1_neon = [
        "Info",
        "Inquiry",
        "Prohibited",
        "Warn",
    ]
    
    media = [
        "CBS",
        "Check Mark",
        "Draft",
        "ESPN",
        "Fox",
        "Heart",
        "Intel>",
        "NBC",
        "Retweet",
        "Tostitos",
        "Tweet",
        "Twitch",
        "Verizon",
        "XMark",
    ]
    
    devtraits = [
        "Hidden Dev trait",
        "Normal Dev trait",
        "Star Dev trait",
        "Super Star Dev Trait",
        "Super Star X Factor",
    ]